
-- Constants
	GoGo_Variables.Localize.ApprenticeRiding = 33388  -- 75 Riding Skill
	GoGo_Variables.Localize.AquaForm = 1066
	GoGo_Variables.Localize.ArtisanRiding = 34091  -- 300 Riding skill
	GoGo_Variables.Localize.AspectCheetah = 186257
	GoGo_Variables.Localize.AspectPack = 13159
--	GoGo_Variables.Localize.AzerothianNavigation = 90269  -- changed during beta to 90267
	GoGo_Variables.Localize.BfaPathFinder2 = 278833
--	GoGo_Variables.Localize.BrokenIslesPathFinder = 233368 -- No longer needed as of patch 9.0
	GoGo_Variables.Localize.CatForm = 768
--	GoGo_Variables.Localize.ColdWeatherFlying = 54197	-- Removed with patch 7.3.5
--	GoGo_Variables.Localize.CloudSerpentRiding = 130487		-- Gone with Warcraft 6.0
	GoGo_Variables.Localize.CrusaderAura = 32223
--	GoGo_Variables.Localize.DraenorPathfinder = 191645 -- Gone with Warcraft 9.0
	GoGo_Variables.Localize.ExpertRiding = 34090  -- 225 Riding skill
	GoGo_Variables.Localize.FastFlightForm = 40120
	GoGo_Variables.Localize.FelineSwiftness = 131768  -- Druid talent
	GoGo_Variables.Localize.FlightForm = 165962  -- Druid talent
--	GoGo_Variables.Localize.FlightMastersLicense = 90267	-- Removed with patch 7.3.5
	GoGo_Variables.Localize.GhostWolf = 2645
	GoGo_Variables.Localize.Glyph_AquaticForm = 57856
	GoGo_Variables.Localize.Glyph_Cheetah = 131113  -- Druid's Glyph of the Cheetah
--	GoGo_Variables.Localize.Glyph_GhostWolf = 59289
	GoGo_Variables.Localize.Glyph_Stag = 114338  -- Druid's Glyph of the Stag
	GoGo_Variables.Localize.JourneymanRiding = 33391  -- 150 Riding Skill
	GoGo_Variables.Localize.MasterRiding = 90265  -- 300 Riding Skill + 310% speed
	GoGo_Variables.Localize.MemoriesOfSunlessSkies = 63727
	GoGo_Variables.Localize.MountForm = 210053
	GoGo_Variables.Localize.NightFae = 3
	GoGo_Variables.Localize.NoCovenant = 0
	GoGo_Variables.Localize.RunningWild = 87840
	GoGo_Variables.Localize.SeaLegs = 73701
	GoGo_Variables.Localize.Skill.ApprenticeRiding = 75
	GoGo_Variables.Localize.Skill.ArtisanRiding = 300
	GoGo_Variables.Localize.Skill.ExpertRiding = 225
	GoGo_Variables.Localize.Skill.JourneymanRiding = 150
	GoGo_Variables.Localize.Skill.MasterRiding = 325
	GoGo_Variables.Localize.Skill.NoRiding = 0
	GoGo_Variables.Localize.SoulShape = 310143 -- Night Fae Signature Ability
	GoGo_Variables.Localize.TheTrueMawWalker = 353214
	GoGo_Variables.Localize.TheTrueMawWalkerQuest = 63663
	GoGo_Variables.Localize.TravelForm = 783 -- Druid talent
	GoGo_Variables.Localize.TravelForm2 = 33943 -- Druid talent
	GoGo_Variables.Localize.UnlockingTheSecret = 15514 -- Flying in Zereth Morthis
--	GoGo_Variables.Localize.WisdomOfTheFourWinds = 115913	-- Removed with patch 7.3.5
	GoGo_Variables.Localize.ZenFlight = 125883  -- Spell in book appears for monks with glyph of zen flight
